name: daily_planner
description: "A mindful daily planner app with task management and category organization."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # PDF Generation
  pdf: ^3.10.8
  printing: ^5.12.0
  
  # Path and File handling
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # Date and Time utilities
  intl: ^0.19.0
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # Calendar
  table_calendar: ^3.0.9
  
  # File sharing
  share_plus: ^7.2.2
  
  # URL launcher
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Build runner for Hive
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
    
  fonts:
    - family: Handwritten
      fonts:
        - asset: assets/fonts/handwritten.ttf
